### ISSUE TITLE
bug in mod manager section 

### ISSUE THREAD

**Issue by NuxArden** [NRTnarathip/SMAPILoader#13]
Hi, I'm having a bug in the mod manager section of my SMAPI app.
I hope this bug can be fixed🙏
BTW, my phone is a Samsung.
Here's the error log:

Java.Lang.SecurityException: com.samsung.android.providers.media has no access to content://media/external_primary/file/1000825390
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualObjectMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
   at Android.Content.ContentResolver.OpenInputStream(Uri uri)
   at Xamarin.Essentials.FileSystem.OpenContentStream(Uri uri, String& extension)
   at Xamarin.Essentials.FileSystem.CacheContentFile(Uri uri)
   at Xamarin.Essentials.FileSystem.EnsurePhysicalPath(Uri uri, Boolean requireExtendedAccess)
   at Xamarin.Essentials.FilePicker.<>c__DisplayClass2_0.<PlatformPickAsync>g__OnResult|0(Intent intent)
   at Xamarin.Essentials.IntermediateActivity.OnActivityResult(Int32 requestCode, Result resultCode, Intent data)
--- End of stack trace from previous location ---
   at Xamarin.Essentials.FilePicker.PlatformPickAsync(PickOptions options, Boolean allowMultiple)
   at Xamarin.Essentials.FilePicker.PickAsync(PickOptions options)
   at SMAPIGameLoader.FilePickerTool.PickZipFile(String title)
   at SMAPIGameLoader.Launcher.ModInstaller.OnClickInstallMod(Action OnInstalledCallback)
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: com.samsung.android.providers.media has no access to content://media/external_primary/file/1000825390
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at crc64a0e0a82d0db9a07d.IntermediateActivity.n_onActivityResult(Native Method)
	at crc64a0e0a82d0db9a07d.IntermediateActivity.onActivityResult(IntermediateActivity.java:48)
	at android.app.Activity.dispatchActivityResult(Activity.java:8951)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5987)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6033)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: com.samsung.android.providers.media has no access to content://media/external_primary/file/1000825390
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at crc64a0e0a82d0db9a07d.IntermediateActivity.n_onActivityResult(Native Method)
	at crc64a0e0a82d0db9a07d.IntermediateActivity.onActivityResult(IntermediateActivity.java:48)
	at android.app.Activity.dispatchActivityResult(Activity.java:8951)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5987)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6033)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by NRTnarathip** [comment]
android version?
and phone model name?

**Comment by NuxArden** [comment]
Android 13
Samsung Galaxsi A04e

**Comment by NRTnarathip** [comment]
Hello, and now do you have fix it?
